# -*- coding: utf-8 -*-
"""food system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PE8m_8D7oPs-ZDRfA7TcpAefs_1tj6GQ
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

path = "/content/drive/MyDrive/food project/food.csv"
df = pd.read_csv(path)

df.head()

print("Shape:", df.shape)

df.head()

df.info()

df.describe()

df.isnull().sum()

df.columns = df.columns.str.strip().str.replace(" ", "_")
print(df.columns)

print("Duplicates before:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates after:", df.duplicated().sum())

df.fillna(df.mean(numeric_only=True), inplace=True)

df["Category"] = df["Category"].fillna("Unknown")

df.isnull().sum()

# Clean column names
df.columns = df.columns.str.strip().str.replace(" ", "_")

# Rename dataset columns to project standard names
df = df.rename(columns={
    "dish_name": "Food_Item"
})

print(df.columns)

df = df.rename(columns={
    "Dish_Name": "Food_Item",
    "Calories_(kcal)": "Calories_per_100g",
    "Protein_(g)": "Protein_g",
    "Calcium_(mg)": "Calcium_mg",
    "Iron_(mg)": "Iron_mg",
    "Vitamin_C_(mg)": "Vitamin_C_mg"
})

print(df.columns)

df["Food_Item"] = df["Food_Item"].str.lower().str.strip()

food_map = {
    "kozhi curry": "chicken curry",
    "murg curry": "chicken curry",
    "chicken masala": "chicken curry",
    "veg pulao": "vegetable pulao",
    "paneer gravy": "paneer curry"
}

df["Food_Item"] = df["Food_Item"].replace(food_map)

df = df.drop_duplicates(subset="Food_Item")
df.head()

df.isnull().sum()
df.fillna(df.mean(numeric_only=True), inplace=True)

import matplotlib.pyplot as plt

df["Calorie_Level"] = pd.cut(
    df["Calories_per_100g"],
    bins=[0,150,300,1000],
    labels=["Low Calorie","Medium Calorie","High Calorie"]
)

plt.figure()
df["Calorie_Level"].value_counts().plot(kind="pie", autopct='%1.1f%%')
plt.title("How Foods Are Distributed By Calories")
plt.ylabel("")
plt.show()

nutrient_avg = [
    df["Protein_g"].mean(),
    df["Iron_mg"].mean(),
    df["Calcium_mg"].mean(),
    df["Vitamin_C_mg"].mean()
]

labels = ["Protein","Iron","Calcium","Vitamin C"]

plt.figure()
plt.bar(labels, nutrient_avg)
plt.title("Average Nutrient Levels in Indian Foods")
plt.ylabel("Average Value")
plt.show()

features = df[[
    "Food_Item",
    "Category",
    "Calories_per_100g",
    "Protein_g",
    "Iron_mg",
    "Calcium_mg",
    "Vitamin_C_mg"
]]

features.head()

features.to_csv("/content/drive/MyDrive/food project/clean_food_dataset.csv", index=False)

# Load cleaned dataset for recommendation system
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/drive/MyDrive/food project/clean_food_dataset.csv")

df.head()

# BMI calculation
def calculate_bmi(weight, height):
    height_m = height / 100
    bmi = weight / (height_m ** 2)
    return round(bmi, 2)

def bmi_category(bmi):
    if bmi < 18.5:
        return "Underweight"
    elif 18.5 <= bmi < 25:
        return "Normal"
    elif 25 <= bmi < 30:
        return "Overweight"
    else:
        return "Obese"

# Predict nutrient deficiency from symptoms
def predict_deficiency(symptoms):
    symptoms = symptoms.lower()

    if "tired" in symptoms or "hairfall" in symptoms:
        return "Iron"
    elif "weak" in symptoms or "muscle" in symptoms:
        return "Protein"
    elif "bone" in symptoms:
        return "Calcium"
    elif "cold" in symptoms or "immunity" in symptoms:
        return "Vitamin C"
    else:
        return "General"

# Food recommendation based on deficiency
def recommend_foods(deficiency, diet_type):

    # filter vegetarian / non-veg
    if diet_type.lower() == "vegetarian":
        filtered = df[df["Category"] == "Vegetarian"]
    else:
        filtered = df.copy()

    # sort foods based on deficiency
    if deficiency == "Protein":
        foods = filtered.sort_values("Protein_g", ascending=False)

    elif deficiency == "Iron":
        foods = filtered.sort_values("Iron_mg", ascending=False)

    elif deficiency == "Calcium":
        foods = filtered.sort_values("Calcium_mg", ascending=False)

    elif deficiency == "Vitamin C":
        foods = filtered.sort_values("Vitamin_C_mg", ascending=False)

    else:
        foods = filtered.sort_values("Calories_per_100g", ascending=False)

    return foods.head(5)

# Visualization for recommended foods
def plot_nutrient_graph(recommended_foods):

    nutrients = ["Protein_g","Iron_mg","Calcium_mg","Vitamin_C_mg"]
    avg_values = recommended_foods[nutrients].mean()

    plt.figure()
    plt.bar(["Protein","Iron","Calcium","Vitamin C"], avg_values)
    plt.title("Nutrients You Will Get From Recommended Foods")
    plt.ylabel("Average Nutrient Value")
    plt.show()

print("---------------------------------------------------")
print("        PERSONALIZED NUTRITION SYSTEM")
print("---------------------------------------------------")

age = int(input("Enter your age: "))
gender = input("Enter your gender (Male/Female): ")
height = float(input("Enter your height (cm): "))
weight = float(input("Enter your weight (kg): "))
diet_type = input("Enter diet type (Vegetarian/Non-Vegetarian): ")

know_def = input("Do you already know your deficiency? (Yes/No): ")

if know_def.lower() == "yes":
    deficiency = input("Enter deficiency (Protein/Iron/Calcium/Vitamin C): ")
else:
    symptoms = input("Enter your symptoms (example: tired, weak bones): ")
    deficiency = predict_deficiency(symptoms)

# BMI calculation
bmi = calculate_bmi(weight, height)
bmi_status = bmi_category(bmi)

# Get food recommendations
recommended = recommend_foods(deficiency, diet_type)

# ---------------- RESULT OUTPUT ----------------
print("\n---------------------------------------------------")
print("           PERSONALIZED NUTRITION REPORT")
print("---------------------------------------------------")
print("Age:", age)
print("Gender:", gender)
print("Height:", height, "cm")
print("Weight:", weight, "kg")
print("BMI:", bmi)
print("BMI Category:", bmi_status)
print("Predicted Deficiency:", deficiency)

print("\nTop Recommended Foods:")
print(recommended[[
    "Food_Item",
    "Protein_g",
    "Iron_mg",
    "Calcium_mg",
    "Vitamin_C_mg",
    "Calories_per_100g"
]])

# Show nutrient chart
plot_nutrient_graph(recommended)